[package]
name = "codefact"
description = "a command-line tool for keeping a fresh CodeArtifact auth token"
version = "1.0.1"
edition = "2024"
authors = ["C J Silverio <ceejceej@gmail.com>"]
license = "Parity-7.0.0"
readme = "README.md"
repository = "https://github.com/ceejbot/codefact"
homepage = "https://github.com/ceejbot/codefact"

[dependencies]
anyhow = "1.0.97"
aws-config = "1.6.1"
aws-sdk-codeartifact = "1.67.0"
aws-sdk-sts = { version = "1.65.0", features = ["behavior-version-latest"] }
home = "0.5.11"
humanize-duration = "0.0.7"
jiff = "0.2.6"
owo-colors = "4.2.1"
regex = "1.11.1"
tokio = { version = "1.44.2", features = ["full"] }

[lints.rust]
unsafe_code = { level = "deny", priority = 1 }
future_incompatible = { level = "deny", priority = 2 }
trivial_casts = { level = "warn", priority = 3 }
rust_2018_idioms = { level = "warn", priority = 4 }

[lints.clippy]
unwrap_used = "deny"

[profile.release]
lto = "thin"
