set -xU AWS_CODEARTIFACT_TOKEN "{token}"
set -xU CODEARTIFACT_TOKEN_EXPIRY "{expiry_ms}"
set -xU UV_DEFAULT_INDEX "https://aws:{token}@{domain}-{account_id}.d.codeartifact.{region}.amazonaws.com/pypi/{repository}/simple/"
set -xU UV_PUBLISH_URL "https://{domain}-{account_id}.d.codeartifact.{region}.amazonaws.com/pypi/{repository}"
set -xU UV_PUBLISH_PASSWORD "{token}"
