name: release
permissions:
    "contents": "write"

on:
    push:
        tags:
            - "v**[0-9]+.[0-9]+.[0-9]+*"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: get stable + nightly Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: nightly, stable
                  components: clippy, rustfmt
                  cache-key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
                  cache-directories: |
                      ~/.cargo/registry
                      ~/.cargo/bin
                      target

            - name: get cargo-nextest on path
              run: |
                  if [[ -z $(which cargo-nextest) ]]; then
                    curl -sL https://get.nexte.st/latest/linux -o nextest.tgz
                    tar xfz nextest.tgz
                    mv cargo-nextest ~/.cargo/bin
                    rm nextest.tgz
                  fi

            - name: run the tests
              run: cargo +stable nextest run

            - name: consult Clippy
              run: cargo +stable clippy --all-targets

            - name: check formatting
              run: cargo +nightly fmt --check --all

            - name: build for release
              run: cargo +stable build --release

            - name: create github release
              run: |
                  tar czf codefact-aarch64-apple-darwin.tar.gz --strip-components=2  target/release/codefact
                  release_url=$(gh release create ${{ github.ref_name }} --generate-notes)
                  gh release upload ${{ github.ref_name }} codefact-aarch64-apple-darwin.tar.gz
                  gh release edit ${{ github.ref_name }} --draft=false
